# Generated by Django 2.2.2 on 2019-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=256, verbose_name='tail_number')),
                ('track_model', models.CharField(max_length=256, verbose_name='track_model')),
                ('max_load_capacity', models.IntegerField(verbose_name='load_capacity')),
                ('current_weight', models.IntegerField(verbose_name='current_weight')),
            ],
        ),
        migrations.CreateModel(
            name='TracksChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trk_model', models.CharField(max_length=256, verbose_name='track_choice_model')),
            ],
        ),
    ]
